# Generated by Django 5.2 on 2025-09-18 03:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0003_delete_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='VAT rate as percentage (e.g., 21.00 for 21%)', max_digits=5)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=10)),
                ('processing_notes', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='receipts_user_id_254d35_idx'), models.Index(fields=['user', 'uploaded_at'], name='receipts_user_id_7ed6bb_idx')],
            },
        ),
    ]
