# Generated by Django 5.2 on 2025-09-23 12:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0003_delete_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VATReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('output_vat_standard', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('output_vat_reduced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('output_vat_zero', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('input_vat_standard', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('input_vat_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sales_standard_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sales_reduced_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sales_zero_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sales_exempt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('purchases_standard_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('purchases_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('previous_corrections', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_output_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_input_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=10)),
                ('due_date', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vat_returns',
                'ordering': ['-year', '-period'],
                'unique_together': {('user', 'period', 'year')},
            },
        ),
        migrations.CreateModel(
            name='VATReturnLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('original_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjusted_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
                ('vat_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='vat_returns.vatreturn')),
            ],
            options={
                'db_table': 'vat_return_line_items',
                'unique_together': {('vat_return', 'transaction')},
            },
        ),
    ]
