# Generated by Django 5.2 on 2025-09-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='accounting_year',
            field=models.CharField(choices=[('calendar', 'Calendar Year (Jan–Dec)'), ('fiscal', 'Fiscal Year (Custom)')], default='calendar', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='Example: +92 03001234567', max_length=20),
        ),
    ]
