# Generated by Django 5.2 on 2025-09-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businessprofile_accounting_year_businessprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('nl', 'Dutch'), ('en', 'English'), ('de', 'German')], default='en', max_length=20),
        ),
    ]
