# Generated by Django 5.2 on 2025-09-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.TextField(blank=True, default='---------------', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(blank=True, default='---------------', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='country',
            field=models.CharField(blank=True, default='---------------', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(blank=True, default='---------------', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='postal_code',
            field=models.CharField(blank=True, default='---------------', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='vat_number',
            field=models.CharField(blank=True, default='---------------', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='website',
            field=models.URLField(blank=True, default='---------------', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='---------------', max_length=20),
        ),
    ]
