# Generated by Django 5.2 on 2025-09-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_businessprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='website',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='legal_form',
            field=models.CharField(choices=[('zzp', 'Sole Proprietorship'), ('bv', 'Private Limited Company (B.V.)'), ('nv', 'Public Limited Company (N.V.)'), ('vof', 'General Partnership (V.O.F.)'), ('cv', 'Limited Partnership (C.V.)'), ('foundation', 'Foundation'), ('association', 'Association')], max_length=20),
        ),
    ]
