# Generated by Django 5.2 on 2025-09-11 16:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT rate as percentage (e.g., 21.00 for 21%)', max_digits=5),
        ),
    ]
