# Generated by Django 5.2 on 2025-09-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_vat_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
